# Generated by Django 5.1.3 on 2026-04-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customer',
            name='tag',
            field=models.CharField(blank=True, choices=[('', '—'), ('vip', 'VIP Customer'), ('frequent', 'Frequent Buyer'), ('new', 'New')], default='', max_length=16),
        ),
    ]
