# Generated by Django 5.1.3 on 2026-04-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
